### ISSUE TITLE
Access to the trained models

### ISSUE THREAD

**Issue by tchewik** [NLP-Discourse-SoochowU/sota_end2end_parser#2]
Hi! The Baidu seems to be unavailable outside of China. Would it be possible to make the weights available somewhere else? Thank you very much

**Comment by NLP-Discourse-SoochowU** [comment]
I'll upload it elsewhere soon and let you know when I'm done. 😄

**Comment by NLP-Discourse-SoochowU** [comment]
Hi Elena,

You can download the files through the following link:
https://www.dropbox.com/scl/fo/6enamgjrqzifux44udpk7/h?dl=0&rlkey=f18zdqtrtxgmctbwvpdq6r0qu

**Comment by tchewik** [comment]
Thanks!
